language: node_js
node_js:
  - "node"
cache:
  npm: true
  directories:
    - ~/.cache
install:
  - npm ci
  - npm run build
before_script:
  - npm start & wait-on http://localhost:3000
script:
  - $(npm bin)/cypress run
